# Generated by Django 5.1.3 on 2024-11-29 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalogKsiazek', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookshelf',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=128),
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='katalogKsiazek.book')),
            ],
        ),
        migrations.CreateModel(
            name='BookRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(choices=[(0, 'brak oceny'), (1, '1 gwiazdka'), (2, '2 gwiazdki'), (3, '3 gwiazdki'), (4, '4 gwiazdki'), (5, '5 gwiazdki')])),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='katalogKsiazek.book')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='katalogKsiazek.bookcategory')),
            ],
        ),
        migrations.CreateModel(
            name='BookStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[('unread', 'Nieprzeczytana'), ('reading', 'W trakcie czytania'), ('read', 'Przeczytana'), ('borrowed', 'Wypożyczona')])),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='katalogKsiazek.book')),
            ],
        ),
    ]
