# Generated by Django 5.1.3 on 2024-11-30 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalogKsiazek', '0002_book_bookshelf_book_rate_alter_book_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrating',
            name='category',
        ),
        migrations.AlterField(
            model_name='bookrating',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='katalogKsiazek.book'),
        ),
    ]
