# Generated by Django 5.1.3 on 2024-12-01 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalogKsiazek', '0003_remove_bookrating_category_alter_bookrating_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrating',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='katalogKsiazek.bookcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookrating',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='katalogKsiazek.book'),
        ),
    ]
