# Generated by Django 5.1.3 on 2024-12-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalogKsiazek', '0004_bookrating_category_alter_bookrating_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookshelf',
            field=models.IntegerField(choices=[(1, 'Półka 1'), (2, 'Półka 2'), (3, 'Półka 3'), (4, 'Półka 4'), (5, 'Półka 5'), (6, 'Półka 6'), (7, 'Półka 7')], default=1),
        ),
    ]
