# Generated by Django 5.1.3 on 2024-12-06 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalogKsiazek', '0005_alter_book_bookshelf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrating',
            name='category',
        ),
        migrations.AlterField(
            model_name='bookrating',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='katalogKsiazek.book'),
        ),
        migrations.AlterField(
            model_name='bookstatus',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='katalogKsiazek.book'),
        ),
        migrations.AlterField(
            model_name='bookstatus',
            name='status',
            field=models.CharField(choices=[('unread', 'Nieprzeczytana'), ('reading', 'W trakcie czytania'), ('read', 'Przeczytana'), ('borrowed', 'Wypożyczona')], max_length=10),
        ),
    ]
